version: "3.8"
services:
  mongodb:
    container_name: chat-mongodb
    ports:  # Uncomment this to access mongodb from outside docker, not safe in deployment
      - 27018:27017
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.7.3
    restart: always
    ports: # Uncomment this to access meilisearch from outside docker
      - 7700:7700 # if exposing these ports, make sure your master key is not the default value
    env_file:
      - .env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.7:/meili_data
  vectordb:
    image: ankane/pgvector:latest
    env_file:
      - .env
    restart: always
    volumes:
      - pgdata2:/var/lib/postgresql/data
  #rag_api:
  #  container_name: rag_api
  #  image: ghcr.io/danny-avila/librechat-rag-api-dev:latest
  #  extra_hosts:
  #    - "host.docker.internal:host-gateway"
  #  ports:
  #    - 8000:8000
  #  environment:
  #    - DB_HOST=vectordb
  #    - RAG_PORT=${RAG_PORT:-8000}
  #  restart: always
  #  depends_on:
  #    - vectordb
  #  env_file:
  #    - .env
  #api:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #    target: api-build
  #  container_name: genai
  #  ports:
  #    - 3080:3080
  #  depends_on:
  #    - mongodb
  #  restart: always
  #  env_file:
  #    - .env
  #  extra_hosts:
  #    - "host.docker.internal:host-gateway"
  #  environment:
  #    - HOST=0.0.0.0
  #    - MONGO_URI=mongodb://mongodb:27017/LibreChat
  #    - MEILI_HOST=http://meilisearch:7700
  #  volumes:
  #    - type: bind
  #      source: ./.env
  #      target: /app/.env
  #    - ./images:/app/client/public/images
  #    - ./logs:/app/api/logs
volumes:
  pgdata2: