apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-branding-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: go-genai-studio-dev-assets-bucket
  claimRef:
    name: api-branding-pvc
    namespace: go-genai-studio-dev