apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - args:
            - mongod
            - --noauth
          image: mongo
          resources:
            requests:
              cpu: 10m
              memory: 512Mi
          name: chat-mongodb
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-claim0
          ports:
            - containerPort: 27017
      restartPolicy: Always
      volumes:
        - name: mongodb-claim0
          persistentVolumeClaim:
            claimName: mongodb-claim0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-service
  name: mongodb-service

spec:
  ports:
    - name: "tcp"
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mongodb-claim0
  name: mongodb-claim0

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
